replicaCount : 2

image: 
  repository: subhadhal/todo-service
  tag: latest
  pullPolicy: Always

service: 
  type: ClusterIP
  port: 80

containerPort: 8000

readinessProbe:
  enabled: true
  path: /todos
  initialDelaySeconds: 5
  periodSeconds: 5

resources: {}
